import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Url } from './url';

const UrlList = () => (
  <>
    <CardHeader className="text-center">
      <CardTitle>Shortened URLs list</CardTitle>
    </CardHeader>
    <Card>
      <CardContent className="flex h-[250px] gap-4 overflow-y-auto">
        <ul className="mt-4 w-full flex-col overflow-y-auto">
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
          <Url
            shortenedUrl="zaza"
            originalUrl="zazazaazza"
          />
        </ul>
      </CardContent>
    </Card>
  </>
);

export default UrlList;
